export {
  fetchScaffoldProjects,
  previewScaffold,
  submitScaffold,
  type BackendTemplateId,
  type BundleTopology,
  type DbTemplateId,
  type FrontendTemplateId,
  type ScaffoldMode,
  type ScaffoldPreviewFile,
  type ScaffoldPreviewResponse,
  type ScaffoldProjectInfo,
  type ScaffoldServiceRequest,
  type ScaffoldSubmitResponse,
  type TemplateId,
} from '@/lib/api'
