#!/usr/bin/env python3
from __future__ import annotations

import argparse
from dataclasses import asdict
import json
import os
from pathlib import Path

import psycopg

from app.db import get_psycopg_database_url
from app.projects_backfill import (
    LegacyProjectRow,
    MigrationPlanRow,
    RegistryRow,
    build_migration_plan,
    build_targets_from_legacy_projects,
)


def _sql_quote(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def _fetch_legacy_projects(conn: psycopg.Connection) -> list[LegacyProjectRow]:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT id, name, environment
            FROM projects
            ORDER BY id ASC
            """
        )
        rows = cur.fetchall()
    return [
        LegacyProjectRow(project_id=row[0], name=row[1], environment=row[2])
        for row in rows
    ]


def _fetch_existing_registry_rows(conn: psycopg.Connection) -> list[RegistryRow]:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT service_id, service_name, namespace, env, app_label, argo_app_name, source, source_ref, last_synced_at
            FROM service_registry
            ORDER BY service_id ASC, env ASC
            """
        )
        rows = cur.fetchall()
    return [
        RegistryRow(
            service_id=row[0],
            service_name=row[1],
            namespace=row[2],
            env=row[3],
            app_label=row[4],
            argo_app_name=row[5],
            source=row[6],
            source_ref=row[7],
            last_synced_at=row[8],
        )
        for row in rows
    ]


def _apply_plan(conn: psycopg.Connection, plan: list[MigrationPlanRow]) -> None:
    with conn.cursor() as cur:
        for item in plan:
            if item.action == "noop":
                continue
            if item.action == "update_rekey" and item.previous is not None:
                target = item.target
                previous = item.previous
                cur.execute(
                    """
                    UPDATE service_registry
                    SET service_id = %s,
                        service_name = %s,
                        namespace = %s,
                        app_label = %s,
                        argo_app_name = %s,
                        source = %s,
                        source_ref = %s,
                        last_synced_at = %s,
                        updated_at = CURRENT_TIMESTAMP
                    WHERE service_id = %s AND env = %s
                    """,
                    (
                        target.service_id,
                        target.service_name,
                        target.namespace,
                        target.app_label,
                        target.argo_app_name,
                        target.source,
                        target.source_ref,
                        target.last_synced_at,
                        previous.service_id,
                        previous.env,
                    ),
                )
                continue
            target = item.target
            cur.execute(
                """
                INSERT INTO service_registry (
                    service_id,
                    service_name,
                    namespace,
                    env,
                    app_label,
                    argo_app_name,
                    source,
                    source_ref,
                    last_synced_at
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (service_id, env) DO UPDATE
                SET service_name = EXCLUDED.service_name,
                    namespace = EXCLUDED.namespace,
                    app_label = EXCLUDED.app_label,
                    argo_app_name = EXCLUDED.argo_app_name,
                    source = EXCLUDED.source,
                    source_ref = EXCLUDED.source_ref,
                    last_synced_at = EXCLUDED.last_synced_at,
                    updated_at = CURRENT_TIMESTAMP
                """,
                (
                    target.service_id,
                    target.service_name,
                    target.namespace,
                    target.env,
                    target.app_label,
                    target.argo_app_name,
                    target.source,
                    target.source_ref,
                    target.last_synced_at,
                ),
            )


def _build_rollback_sql(plan: list[MigrationPlanRow]) -> str:
    lines: list[str] = [
        "-- Rollback SQL generated by migrate_projects_to_service_registry.py",
        "BEGIN;",
    ]
    for item in plan:
        if item.action == "insert":
            lines.append(
                "DELETE FROM service_registry WHERE service_id = '{service_id}' AND env = '{env}';".format(
                    service_id=item.target.service_id.replace("'", "''"),
                    env=item.target.env.replace("'", "''"),
                )
            )
        elif item.action == "update" and item.previous is not None:
            previous = item.previous
            lines.append(
                (
                    "UPDATE service_registry "
                    "SET service_name = '{service_name}', namespace = '{namespace}', app_label = '{app_label}', "
                    "argo_app_name = {argo_app_name}, source = '{source}', source_ref = {source_ref}, "
                    "last_synced_at = {last_synced_at} "
                    "WHERE service_id = '{service_id}' AND env = '{env}';"
                ).format(
                    service_name=previous.service_name.replace("'", "''"),
                    namespace=previous.namespace.replace("'", "''"),
                    app_label=previous.app_label.replace("'", "''"),
                    argo_app_name=_sql_quote(previous.argo_app_name),
                    source=previous.source.replace("'", "''"),
                    source_ref=_sql_quote(previous.source_ref),
                    last_synced_at=_sql_quote(
                        previous.last_synced_at.isoformat()
                        if previous.last_synced_at
                        else None
                    ),
                    service_id=previous.service_id.replace("'", "''"),
                    env=previous.env.replace("'", "''"),
                )
            )
        elif item.action == "update_rekey" and item.previous is not None:
            previous = item.previous
            lines.append(
                (
                    "UPDATE service_registry "
                    "SET service_id = '{service_id}', service_name = '{service_name}', namespace = '{namespace}', "
                    "app_label = '{app_label}', argo_app_name = {argo_app_name}, source = '{source}', "
                    "source_ref = {source_ref}, last_synced_at = {last_synced_at} "
                    "WHERE service_id = '{previous_service_id}' AND env = '{env}';"
                ).format(
                    service_id=previous.service_id.replace("'", "''"),
                    service_name=previous.service_name.replace("'", "''"),
                    namespace=previous.namespace.replace("'", "''"),
                    app_label=previous.app_label.replace("'", "''"),
                    argo_app_name=_sql_quote(previous.argo_app_name),
                    source=previous.source.replace("'", "''"),
                    source_ref=_sql_quote(previous.source_ref),
                    last_synced_at=_sql_quote(
                        previous.last_synced_at.isoformat()
                        if previous.last_synced_at
                        else None
                    ),
                    previous_service_id=item.target.service_id.replace("'", "''"),
                    env=previous.env.replace("'", "''"),
                )
            )
    lines.append("COMMIT;")
    return "\n".join(lines) + "\n"


def _summarize(plan: list[MigrationPlanRow]) -> dict[str, int]:
    return {
        "insert": sum(1 for item in plan if item.action == "insert"),
        "update": sum(1 for item in plan if item.action == "update"),
        "update_rekey": sum(1 for item in plan if item.action == "update_rekey"),
        "noop": sum(1 for item in plan if item.action == "noop"),
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "One-time migration from legacy projects rows to canonical service_registry rows."
        )
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Apply changes to service_registry. Default is dry-run report only.",
    )
    parser.add_argument(
        "--namespace",
        default=os.getenv("PROJECTS_DEFAULT_NAMESPACE", "default"),
        help="Namespace to set for migrated rows (default: PROJECTS_DEFAULT_NAMESPACE or 'default').",
    )
    parser.add_argument(
        "--rollback-file",
        default="",
        help="Optional file path to write generated rollback SQL.",
    )
    args = parser.parse_args()

    with psycopg.connect(get_psycopg_database_url()) as conn:
        legacy_rows = _fetch_legacy_projects(conn)
        existing_rows = _fetch_existing_registry_rows(conn)
        targets = build_targets_from_legacy_projects(
            legacy_rows,
            default_namespace=args.namespace,
        )
        plan = build_migration_plan(targets, existing_rows)
        rollback_sql = _build_rollback_sql(plan)

        report = {
            "dryRun": not args.apply,
            "legacyRows": len(legacy_rows),
            "registryRows": len(existing_rows),
            "summary": _summarize(plan),
            "plan": [
                {
                    "action": item.action,
                    "legacyProjectId": item.target.legacy_project_id,
                    "serviceId": item.target.service_id,
                    "serviceName": item.target.service_name,
                    "env": item.target.env,
                    "namespace": item.target.namespace,
                    "mappingRule": item.target.mapping_rule,
                    "changedFields": list(item.changed_fields),
                }
                for item in plan
            ],
            "rollbackSqlPreview": rollback_sql,
        }

        if args.apply:
            _apply_plan(conn, plan)
            report["applied"] = True
        else:
            report["applied"] = False

        print(json.dumps(report, indent=2, sort_keys=False, default=str))

        if args.rollback_file:
            rollback_path = Path(args.rollback_file)
            rollback_path.write_text(rollback_sql, encoding="utf-8")
            print(f"Wrote rollback SQL to {rollback_path}")


if __name__ == "__main__":
    main()
